### 1. 커피 메뉴 목록 조회 API
GET http://localhost:8080/api/menus
Content-Type: application/json

### 2. 인기 커피 메뉴 조회 API (최근 7일 Top 3)
GET http://localhost:8080/api/menus/popular
Content-Type: application/json

### 3. 포인트 충전 하기 API
POST http://localhost:8080/api/points/charge
Content-Type: application/json

{
  "userId": 1,
  "amount": 10000,
  "chargeRequestId": "req-uuid-1234-5678"
}

### 4. 커피 주문/결제 하기 API
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "userId": 1,
  "menuId": 1,
  "quantity": 2
}
